load(":macro.bzl", "multi_copy_macro")
load(":rule.bzl", "multi_copy_rule")

multi_copy_macro(
    name = "macro_copy",
    srcs = ["file1.txt", "file2.txt"],
)

multi_copy_rule(
    name = "rule_copy",
    srcs = ["file1.txt", "file2.txt"],
)
